# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20160102_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=shop.models.convert_file_name, verbose_name='Изображение'),
        ),
    ]
