# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20160115_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Сортировка')),
                ('image', models.ImageField(default='', upload_to=shop.models.convert_file_name, verbose_name='Изображение')),
                ('newsitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.NewsItem')),
            ],
            options={
                'verbose_name': 'Изображение новости',
                'ordering': ('ordering',),
                'verbose_name_plural': 'Изображения новостей',
            },
        ),
    ]
