# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20160117_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsitem',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='newsitem',
            old_name='title',
            new_name='title_ru',
        ),
    ]
