# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20160127_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='text_en',
            field=models.TextField(default='', verbose_name='Текст (англ.)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_en',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок (англ.)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='text_ru',
            field=models.TextField(default='', verbose_name='Текст (рус.)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title_ru',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок (рус.)'),
        ),
    ]
